version: 2
jobs:
  build:
    working_directory: /home/cbgeo/research/mpm-point-generator
    docker:
      - image: quay.io/cbgeo/mpm3d
    steps:
      - checkout
      # GCC 6.3
      - run:
          name: GCC-6 build
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_EXPORT_COMPILE_COMMANDS=On ..
            make -j8 
            ctest -VV
      # Clang 3.9
      - run:
          name: Clang-3.9 build
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=On ..
            make -j8 
            ctest -VV
      # cppcheck
      - run:
          name: cppcheck
          command: |
            cppcheck --version
            cppcheck --enable=warning --inconclusive --force --language=c++ --std=c++11 src/*.cc include/*.h include/*.tcc --error-exitcode=1
      # codecoverage
      - run:
          name: codecov.io
          command: |
            mkdir -p build
            [ "$(ls -A build)" ] && rm -rf build/*
            cd build
            cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_COMPILER=g++ -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DENABLE_COVERAGE=On ..
            make mpm_point_generator_unit_test -j2
            ./mpm_point_generator_unit_test
            make gcov
            make lcov
            bash <(curl -s https://codecov.io/bash) -X gcov

